name: deploy-on-s3

on:
  workflow_run:
    workflows:
      - main
    branches:
      - main
    types: 
      - completed
     
jobs:
  deploy:
    name: Build And Upload to S3
    runs-on: ubuntu-latest

    steps:
      - name: Make fail if the previous workflow was failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo '::error::Previous workflow was failed'
          exit 1

      - name: Configure AWS credentials from account
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-1
            
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
            
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}

      - name: Copy Files to s3
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          git checkout gh-pages
          
          aws s3 sync . s3://zzztest-s3-14 --exclude "*" --include "index.html" --exact-timestamps 

          aws s3 sync . s3://zzztest-s3-14/SampleDoc --exact-timestamps # 同じファイルサイズでも同期されるように
