name: deploy-on-s3

on:
  workflow_run:
    workflows:
      - main
    branches:
      - main
    types: 
      - completed
     
jobs:
  deploy:
    name: Build And Upload to S3
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v1
      - name: Configure AWS credentials from account
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-1

      - name: Copy Files to s3
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          git branch -M gh-pages

          aws s3 sync . s3://pca-knowledge-base-bucket --exact-timestamps --delete # 同じファイルサイズでも同期されるように
