name: deploy-on-s3

on:
  pull_request:
    branches: 
      - main
  push:
      branches:
        - main
  workflow_dispatch:  # Action タブから任意に実行できるようにする
  
jobs:
  deploy:
    name: Build And Upload to S3
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1  # リポジトリをチェックアウト

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn build
      
      - name: Configure AWS credentials from account
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-1
            
      - name: Copy Files to s3
        run: aws s3 sync ./build s3://pca-knowledge-base-bucket
